// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZxJc3X88GgmolRsvp1Y1P4k5hbTvEHw',
    appId: '1:66469970407:web:58bb151f25f7d8baf4fd42',
    messagingSenderId: '66469970407',
    projectId: 'fitmach-ce9c6',
    authDomain: 'fitmach-ce9c6.firebaseapp.com',
    storageBucket: 'fitmach-ce9c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPZBXCByjxcyGH6YmVdB66gTvpOIrdh0',
    appId: '1:66469970407:android:2f5f4e469ddba8cdf4fd42',
    messagingSenderId: '66469970407',
    projectId: 'fitmach-ce9c6',
    storageBucket: 'fitmach-ce9c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe8EYe8DnoYTQJSaO5n-akcoVLgWjx1W4',
    appId: '1:66469970407:ios:bda4188050ae4000f4fd42',
    messagingSenderId: '66469970407',
    projectId: 'fitmach-ce9c6',
    storageBucket: 'fitmach-ce9c6.firebasestorage.app',
    iosBundleId: 'com.ceduc.fitmach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe8EYe8DnoYTQJSaO5n-akcoVLgWjx1W4',
    appId: '1:66469970407:ios:bda4188050ae4000f4fd42',
    messagingSenderId: '66469970407',
    projectId: 'fitmach-ce9c6',
    storageBucket: 'fitmach-ce9c6.firebasestorage.app',
    iosBundleId: 'com.ceduc.fitmach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZxJc3X88GgmolRsvp1Y1P4k5hbTvEHw',
    appId: '1:66469970407:web:1ddba81e0718eeacf4fd42',
    messagingSenderId: '66469970407',
    projectId: 'fitmach-ce9c6',
    authDomain: 'fitmach-ce9c6.firebaseapp.com',
    storageBucket: 'fitmach-ce9c6.firebasestorage.app',
  );
}
